# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e1f3dca7167ad64d79d9498cb8b173c1baa4c41cf664d69756ab079de01af521df858668dd0ce31d852daa334435d9b046b297e650ca0237413a78ce3002e23

test:
  secret_key_base: 9d736420de9c37873c10878883247f94905d80aee9f99d0ee7ba7b41e761e20f58c90fefcc749667a45f665befe1ba672637a5148e12a55ed1604638c92a6f84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
