class SMS < ActiveRecord::Base
  # :ToCountry,
  # :ToState,
  # :SmsMessageSid,
  # :NumMedia,
  # :ToCity,
  # :FromZip,
  # :SmsSid,
  # :FromState,
  # :SmsStatus,
  # :FromCity,
  # :Body,
  # :FromCountry,
  # :To,
  # :ToZip,
  # :NumSegments,
  # :MessageSid,
  # :AccountSid,
  # :From,
  # :ApiVersion
end